
/* ============================================================
   RICH CMD v7.4.1 — Coaching UX Polish & Learning Quality
   Makes Coaching calmer, more readable and more motivating.
   Keeps existing Coaching data and functions intact.
   ============================================================ */
(function(){
  'use strict';
  try{
    APP.version = 'v7.4.1';
    APP.cache = 'rich-cmd-cache-v741';
    APP.build = 'Coaching UX Polish & Learning Quality';
    APP.pwa = APP.pwa || {};
    APP.pwa.assets = ['./','./index.html','./index.html?v=741','./styles.css?v=741','./vro-data.js?v=741','./app.js?v=741','./manifest.json?v=741','./version.json','./icon-192.png','./icon-512.png'];

    const L741 = (nl,en)=> (typeof currentLang==='function' && currentLang()==='en') ? (en||nl) : nl;
    const E741 = v => (typeof escapeHtml==='function' ? escapeHtml(String(v==null?'':v)) : String(v==null?'':v).replace(/[&<>\"']/g, ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch])));
    const A741 = v => Array.isArray(v) ? v : [];
    const save741 = ()=>{ try{ if(typeof save==='function') save(); else localStorage.setItem(APP.storage, JSON.stringify(state)); }catch(_){ } };
    const render741 = ()=>{ try{ if(typeof render==='function') render(); }catch(_){ } };
    const toast741 = (msg,type='info')=>{ try{ if(typeof toast==='function') toast(msg,type); }catch(_){ console.log(msg); } };
    const modal741 = (title,html,wide)=>{ try{ if(typeof modal==='function') modal(title,html,wide?'wide':''); else alert(title); }catch(_){ alert(title); } };
    const close741 = ()=>{ try{ if(typeof closeModal==='function') closeModal(); }catch(_){ } };
    const copy741 = txt=>{ try{ if(typeof copyText==='function') copyText(txt); else if(navigator.clipboard) navigator.clipboard.writeText(txt); toast741(L741('Gekopieerd','Copied'),'good'); }catch(_){ toast741(L741('Kopiëren niet gelukt','Copy failed'),'warn'); } };

    function ensure741(){
      state.coachingDone = A741(state.coachingDone);
      state.coachingPractices = A741(state.coachingPractices);
      state.coachingExamPassed = A741(state.coachingExamPassed);
      state.coachingBookmarks = A741(state.coachingBookmarks);
      state.coaching741 = state.coaching741 || {path:'all', badgeFilter:'all', showCompleted:false, showHigher:false, currentExam:null, examAnswers:{}};
      state.ui = state.ui || {};
      return state.coaching741;
    }
    function done741(id){ return A741(state.coachingDone).includes(id); }
    function practice741(id){ return A741(state.coachingPractices).includes(id); }
    function examDone741(id){ return A741(state.coachingExamPassed).includes(id) || A741((state.coaching741||{}).passedExams).includes(id); }
    function addActivity741(msg){ try{ if(typeof addActivity==='function') addActivity(msg,'coaching'); }catch(_){ } }

    function paths741(){ return [
      {id:'agf', icon:'🥬', title:L741('AGF vakkennis','Produce expertise'), text:L741('Kwaliteit, hardlopers, restanten, nee-verkoop en bestelgevoel.','Quality, fast movers, leftovers, no-sales and ordering sense.')},
      {id:'haccp', icon:'🛡️', title:'HACCP', text:L741('Voedselveiligheid, dagelijkse basis, bewijs en prioriteiten.','Food safety, daily base, proof and priorities.')},
      {id:'store', icon:'🗺️', title:L741('Store Map & signaleren','Store Map & detecting'), text:L741('Risico’s zien, gradatie begrijpen en opvolging kiezen.','Spotting risks, understanding gradation and choosing follow-up.')},
      {id:'comm', icon:'💬', title:L741('Communicatie','Communication'), text:L741('Kort, duidelijk en opvolgbaar overdragen.','Short, clear and followable handover.')},
      {id:'discipline', icon:'🎯', title:L741('Werkhouding & discipline','Work attitude & discipline'), text:L741('Afmaken, ritme houden en eigenaarschap tonen.','Finishing, keeping rhythm and showing ownership.')},
      {id:'calm', icon:'🌿', title:L741('Rust & stress','Calm & stress'), text:L741('Rustig kiezen onder druk zonder kwaliteit te verliezen.','Choosing calmly under pressure without losing quality.')},
      {id:'customer', icon:'🤝', title:L741('Klantgerichtheid','Customer focus'), text:L741('Vriendelijk blijven en grenzen bewaken.','Staying friendly while keeping boundaries.')},
      {id:'leader', icon:'🧭', title:L741('Leiderschap / Shiftleider Pro','Leadership / Shift Leader Pro'), text:L741('Overzicht houden, verdelen, bijsturen en rapporteren.','Keeping overview, dividing work, adjusting and reporting.')},
      {id:'planning', icon:'🧩', title:L741('Planning & prioriteren','Planning & prioritizing'), text:L741('Weten wat eerst moet en wat veilig later kan.','Knowing what goes first and what can safely wait.')}
    ]; }

    const baseLessons741 = [
      ['agf_quality','agf',1,14,'AGF kwaliteitsronde als vakman','Je leert kwaliteit beoordelen in lagen: presentatie, productkwaliteit, voorraad en acties.','Een goede kwaliteitsronde voorkomt derving, nee-verkoop en klantklachten. Begin zichtbaar, verwijder slechte kwaliteit en noteer één concreet aandachtspunt.','Je vult bananen bij, maar ziet ook trossen met drukplekken. Je haalt slechte kwaliteit weg, vult hardlopers bij en plant een korte einddag-naloop.','Alleen vullen zonder slechte kwaliteit weg te halen. Het schap lijkt vol, maar de klant ziet alsnog slechte producten.','Loop presentatie na|Verwijder slechte kwaliteit|Controleer hardlopers en acties|Noteer één aandachtspunt','Doe één kwaliteitsronde en noteer het product dat de meeste aandacht vraagt.'],
      ['agf_no_sales','agf',2,13,'Nee-verkoop begrijpen','Je leert verschil maken tussen leeg schap, voorraad achter, bestelfout en timingprobleem.','Nee-verkoop is gemiste verkoop én een proces-signaal. Eén leeg moment is een signaal; herhaling wordt pas een patroon.','Komkommer is leeg om 16:30, maar voorraad staat achter. Dan is de oplossing vullen/timing, niet automatisch meer bestellen.','Besteladvies verhogen zonder voorraad achter of timing te controleren.','Controleer schap|Controleer voorraad achter|Bepaal hardloper/actie|Kies vullen, monitoren of bestelcontrole','Registreer één nee-verkoop-signaal en kies de oorzaak.'],
      ['haccp_priority','haccp',1,15,'HACCP-prioriteit: risico vóór planning','Je leert waarom dagelijkse basiscontrole meestal vóór periodiek werk komt.','HACCP gaat om risico beheersen. Temperatuur, zichtbare hygiëne en klantveiligheid zijn basis. Alleen echte urgenties horen daarboven.','Temperaturen zijn nog niet gedaan. Een maandtaak mag wachten, behalve bij direct risico zoals lekkage of schimmel gradatie 2/3.','Periodieke taken oppakken terwijl basisrisico’s nog openstaan.','Check echte urgenties|Rond dagelijkse basis af|Plan periodiek werk|Leg afwijkingen vast','Leg bij één HACCP-keuze vast waarom iets eerst moest.'],
      ['store_signal','store',1,13,'Store Map signaleren zonder paniek','Je leert onderscheid maken tussen baseline, monitoren, aandacht, urgent en kritiek.','Niet elk punt is achterstand. Nieuwe punten zijn baseline tot er controle, planning of signaal is. Schimmel gradatie 2/3 vraagt directe opvolging.','Een klein oppervlakkig plekje is gradatie 1 en wordt gemonitord. Duidelijke schimmel wordt urgent en gaat naar HACCP.','Alles als urgent behandelen, waardoor de planning onrustig wordt.','Bepaal status|Bepaal gradatie|Kies monitoren of HACCP|Plan nacontrole','Classificeer één Store Map-punt met reden.'],
      ['comm_handover','comm',1,12,'Goede overdracht maken','Je leert kort en opvolgbaar communiceren.','Een goede overdracht zegt wat gedaan is, wat open staat, wie iets moet doen en wanneer opvolging nodig is.','“Koeling AGF: temperatuur oké, maar plank M2 morgen nacontroleren” is beter dan “let op AGF”.','Te veel tekst zonder actie of eigenaar.','Schrijf situatie|Schrijf actie|Schrijf open punt|Voeg opvolgdatum toe','Maak één overdracht in vier regels.'],
      ['discipline_finish','discipline',1,12,'Afmaken geeft rust','Je leert waarom afronden, markeren en kort rapporteren werkdruk verlaagt.','Werk voelt drukker als taken half-open blijven. Afvinken of kort noteren maakt vooruitgang zichtbaar.','Je rondt HACCP af, vinkt de fase af en zet één open punt naar morgen.','Alles onthouden in je hoofd en later vergeten waarom iets open bleef.','Kies één taak|Maak hem af of stel bewust uit|Noteer reden|Ga pas dan door','Sluit vandaag één open punt bewust af.'],
      ['calm_pressure','calm',1,14,'Rustig blijven bij werkdruk','Je leert dat rust geen traagheid is, maar kiezen vóór versnellen.','Bij drukte wil je alles tegelijk oplossen. Professioneel werken begint met één juiste volgende stap.','Vracht komt binnen terwijl HACCP open staat. Je kiest eerst risico, daarna winkelbeeld, daarna rest.','Sneller lopen zonder volgorde, waardoor fouten ontstaan.','Stop 10 seconden|Kies risico of klantveiligheid|Kies één taak|Communiceer open punten','Gebruik Wat Nu? en kies bewust één stap.'],
      ['customer_boundary','customer',1,11,'Klantvriendelijk met grenzen','Je leert vriendelijk blijven zonder je werk volledig kwijt te raken.','Klantgerichtheid betekent helpen én overzicht houden. Je kunt duidelijk zijn zonder kortaf te worden.','“Ik help u zo, ik maak dit eerst veilig af” is vriendelijk én duidelijk.','Alles laten vallen zonder prioriteit te bewaken.','Luister|Herhaal kort|Geef duidelijke actie|Pak je werkroute weer op','Bedenk één rustige standaardzin voor drukke momenten.'],
      ['leader_evening','leader',1,15,'Shiftleider overzicht houden','Je leert plannen op mensen, paden, tijd en verstoringen.','Shiftleiderwerk vraagt overzicht: wie staat waar, wat is open, wat verstoort de planning en wat moet in het report?','AGF heeft meer vuluren dan gepland. Je verschuift iemand en noteert de reden.','Alleen reageren op problemen en pas laat zien dat paden open blijven.','Check team|Check paden|Check open taken|Log verstoringen|Maak report','Maak een mini-vulplanning voor drie paden.'],
      ['planning_order','planning',1,13,'Prioriteren met een schuivende dag','Je leert werken met richttijden zonder dat je planning kapot gaat.','Richttijden zijn ankers, geen harde triggers. De volgorde blijft leidend en schuift mee bij vertraging.','HACCP loopt 20 minuten uit. AGF-restanten schuift mee, maar verdwijnt niet.','De planning volledig laten wijzigen door kloktijd.','Gebruik starttijd|Volg route|Vink fases af|Meet alleen als nuttig|Evalueer achteraf','Kies één taak die je vandaag alleen afvinkt, en één die je meet.']
    ];
    function lessons741(){ return baseLessons741.map(x=>({id:'v741_'+x[0], path:x[1], level:x[2], min:x[3], title:L741(x[4],x[4]), goal:L741(x[5],x[5]), why:L741(x[6],x[6]), example:L741(x[7],x[7]), mistake:L741(x[8],x[8]), steps:x[9].split('|').map(s=>L741(s,s)), assignment:L741(x[10],x[10]), reflect:L741('Wat neem je mee naar je volgende werkdag?','What will you use in your next workday?')})); }

    function exams741(){ return [
      {id:'v741_exam_agf', path:'agf', title:L741('AGF basistoets','Produce basics test'), questions:[{q:L741('Wat controleer je eerst bij een leeg AGF-vak?','What do you check first with an empty produce shelf?'), a:[L741('Meteen besteladvies verhogen','Immediately increase order advice'),L741('Voorraad achter en timing controleren','Check back stock and timing'),L741('Niets doen','Do nothing')], c:1, fb:L741('Juist: eerst oorzaak bepalen.','Correct: determine the cause first.')},{q:L741('Wat betekent één leegmoment?','What does one empty moment mean?'), a:[L741('Altijd structureel probleem','Always structural issue'),L741('Een signaal om te beoordelen','A signal to assess'),L741('Altijd fout besteld','Always ordered wrong')], c:1, fb:L741('Juist: één signaal is nog geen patroon.','Correct: one signal is not yet a pattern.')} ]},
      {id:'v741_exam_haccp', path:'haccp', title:L741('HACCP prioriteitstoets','HACCP priority test'), questions:[{q:L741('Wat gaat normaal vóór periodiek werk?','What usually goes before periodic work?'), a:[L741('Dagelijkse basiscontrole','Daily base check'),L741('Maandtaak zonder risico','Monthly task without risk'),L741('Administratie later','Later admin')], c:0, fb:L741('Juist: basisrisico’s eerst.','Correct: base risks first.')},{q:L741('Schimmel gradatie 2 is meestal...','Mold gradation 2 is usually...'), a:[L741('Baseline','Baseline'),L741('Monitoren later','Monitor later'),L741('Urgent opvolgen','Urgent follow-up')], c:2, fb:L741('Juist: gradatie 2 vraagt opvolging.','Correct: gradation 2 requires follow-up.')} ]},
      {id:'v741_exam_comm', path:'comm', title:L741('Communicatie toets','Communication test'), questions:[{q:L741('Wat hoort in een goede overdracht?','What belongs in a good handover?'), a:[L741('Alle details zonder actie','All details without action'),L741('Situatie, actie, open punt en opvolging','Situation, action, open point and follow-up'),L741('Alleen “let op”','Only “pay attention”')], c:1, fb:L741('Juist: maak het opvolgbaar.','Correct: make it followable.')} ]},
      {id:'v741_exam_store', path:'store', title:L741('Store Map signaleringstoets','Store Map detection test'), questions:[{q:L741('Nieuwe neutrale punten zijn standaard...','New neutral points are by default...'), a:[L741('Achterstallig','Overdue'),L741('Baseline','Baseline'),L741('Kritiek','Critical')], c:1, fb:L741('Juist: eerst baseline.','Correct: baseline first.')} ]}
    ]; }

    function focus741(){
      const agfSignals=A741(state.agfSignals||state.agfProductSignals||state.agfAdviceSignals);
      const commOpen=A741(state.communications).filter(c=>!c.done && !c.completed && c.status!=='done').length;
      const tasks=A741(state.tasks).filter(t=>String(t.status||'').toLowerCase().includes('open') || !t.status).length;
      if(agfSignals.length>=2) return {path:'agf', title:L741('AGF-signalen omzetten in vakkennis','Turn produce signals into skill'), why:L741('Je hebt meerdere AGF-signalen. Een AGF-les helpt bij kwaliteit, nee-verkoop en bestelgevoel.','You have multiple produce signals. A produce lesson helps with quality, no-sales and ordering sense.')};
      if(commOpen>1) return {path:'comm', title:L741('Communicatie opvolgbaar maken','Make communication followable'), why:L741('Er staat communicatie open. Een korte overdracht voorkomt dat werk blijft hangen.','Communication is open. A short handover prevents work from lingering.')};
      if(tasks>3) return {path:'haccp', title:L741('Prioriteit en rust in HACCP','Priority and calm in HACCP'), why:L741('Er zijn open taken. Focus op risico, basis en daarna planning.','There are open tasks. Focus on risk, base and then planning.')};
      return {path:'planning', title:L741('Planning die meeschuift','Planning that shifts with you'), why:L741('Je werkdag heeft richttijden. Deze les helpt om volgorde vast te houden zonder klokstress.','Your workday has guide times. This lesson helps keep order without clock stress.')};
    }
    function pathProgress741(path){ const list=lessons741().filter(l=>l.path===path); const done=list.filter(l=>done741(l.id)).length; return {done,total:list.length,pct:Math.round(done/Math.max(1,list.length)*100)}; }
    function level741(){ return Math.max(1, Math.min(12, 1 + Math.floor(A741(state.coachingDone).length/5))); }
    function xp741(){ return A741(state.coachingDone).length*50 + A741(state.coachingPractices).length*20 + A741(state.coachingExamPassed).length*80; }
    function recommended741(){ const f=focus741(); return lessons741().find(l=>l.path===f.path && !done741(l.id)) || lessons741().find(l=>!done741(l.id)) || lessons741()[0]; }

    function progress741(){ const done=A741(state.coachingDone).length; const practices=A741(state.coachingPractices).length; const exams=A741(state.coachingExamPassed).length; const badges=badges741().filter(b=>b.earned).length; return `<section class="v741-progress"><div><span>${E741(L741('Level','Level'))}</span><strong>${level741()}</strong></div><div><span>XP</span><strong>${xp741()}</strong></div><div><span>${E741(L741('Voltooid','Completed'))}</span><strong>${done}</strong></div><div><span>${E741(L741('Praktijk','Practice'))}</span><strong>${practices}</strong></div><div><span>${E741(L741('Toetsen','Tests'))}</span><strong>${exams}</strong></div><div><span>${E741(L741('Badges','Badges'))}</span><strong>${badges}</strong></div></section>`; }
    function filters741(){ const st=ensure741(); return `<div class="card v741-filters"><div class="btn-row"><button class="btn ${st.path==='all'?'primary':''}" data-action="v741-path" data-id="all">${E741(L741('Alles','All'))}</button>${paths741().slice(0,5).map(p=>`<button class="btn ${st.path===p.id?'primary':''}" data-action="v741-path" data-id="${E741(p.id)}">${E741(p.title)}</button>`).join('')}<button class="btn" data-action="v741-toggle-higher">${E741(st.showHigher?L741('Verberg hogere levels','Hide higher levels'):L741('Toon hogere levels','Show higher levels'))}</button><button class="btn" data-action="v741-toggle-completed">${E741(st.showCompleted?L741('Verberg voltooid','Hide completed'):L741('Voltooide taken tonen','Show completed tasks'))}</button></div></div>`; }
    function section741(title, sub, html, open=true, cls=''){ return `<details class="card v741-section ${cls}" ${open?'open':''}><summary><span><strong>${E741(title)}</strong><small>${E741(sub||'')}</small></span><b>⌄</b></summary><div class="v741-section-body">${html}</div></details>`; }
    function recommendedBlock741(){ const l=recommended741(); const f=focus741(); return `<div class="v741-recommend"><div><span class="chip">${E741(L741('Aanbevolen voor jou','Recommended for you'))}</span><h3>${E741(l.title)}</h3><p class="muted small">${E741(f.why)}</p></div><div class="btn-row"><button class="btn primary" data-action="v741-open-lesson" data-id="${E741(l.id)}">${E741(L741('Start les','Start lesson'))}</button><button class="btn" data-action="v741-path" data-id="${E741(l.path)}">${E741(L741('Toon leerpad','Show path'))}</button></div></div>`; }
    function skillTree741(){ return `<div class="v741-skilltree">${paths741().map(p=>{ const pr=pathProgress741(p.id); const active=ensure741().path===p.id; return `<button class="v741-skill ${active?'active':''}" data-action="v741-path" data-id="${E741(p.id)}"><span class="v741-emoji">${p.icon}</span><span><strong>${E741(p.title)}</strong><small>${E741(p.text)}</small><i><em style="width:${pr.pct}%"></em></i></span><b>${pr.pct}%</b></button>`; }).join('')}</div>`; }
    function lessonCard741(l){ const d=done741(l.id), p=practice741(l.id); return `<div class="v741-lesson ${d?'done':''}"><div><span class="chip">${E741((paths741().find(x=>x.id===l.path)||{}).title||l.path)} · ${E741(L741('Level','Level'))} ${l.level}</span><h3>${E741(l.title)}</h3><p>${E741(l.goal)}</p><div class="v741-meta"><span>${l.min}m</span><span>${p?'✓ ':''}${E741(L741('Praktijk','Practice'))}</span><span>${d?'✓ ':''}${E741(L741('Les','Lesson'))}</span></div></div><div class="btn-row"><button class="btn primary" data-action="v741-open-lesson" data-id="${E741(l.id)}">${E741(L741('Open','Open'))}</button><button class="btn" data-action="v741-practice" data-id="${E741(l.id)}">✓ ${E741(L741('Praktijk','Practice'))}</button></div></div>`; }
    function lessonsBlock741(){ const st=ensure741(); let list=lessons741(); if(st.path!=='all') list=list.filter(l=>l.path===st.path); if(!st.showHigher) list=list.filter(l=>l.level<=level741()+1); if(!st.showCompleted) list=list.filter(l=>!done741(l.id)); return `<div class="v741-lesson-list">${list.map(lessonCard741).join('') || `<p class="muted">${E741(L741('Geen lessen in deze filter. Toon voltooid of kies alles.','No lessons in this filter. Show completed or choose all.'))}</p>`}</div>`; }
    function examCard741(ex){ const d=examDone741(ex.id); return `<div class="v741-exam ${d?'done':''}"><span class="chip">${E741((paths741().find(p=>p.id===ex.path)||{}).title||ex.path)}</span><h3>${E741(ex.title)}</h3><p class="muted small">${E741(L741('Start rustig. Na afloop zie je score, feedback en leeradvies.','Start calmly. Afterwards you see score, feedback and advice.'))}</p><button class="btn primary" data-action="v741-open-exam" data-id="${E741(ex.id)}">${E741(d?L741('Opnieuw maken','Retake'):L741('Start toets','Start test'))}</button></div>`; }
    function examsBlock741(){ return `<div class="grid grid-2">${exams741().map(examCard741).join('')}</div>`; }
    function badges741(){ const done=A741(state.coachingDone).length, practices=A741(state.coachingPractices).length, exams=A741(state.coachingExamPassed).length; return [
      {id:'starter',icon:'🌱',cat:'Basis',tier:'basis',title:L741('Eerste stap','First step'),text:L741('Je bent begonnen met leren.','You started learning.'),progress:Math.min(100,done*100),earned:done>=1,how:L741('Rond één les af.','Complete one lesson.')},
      {id:'practice',icon:'🛠️',cat:'Praktijk',tier:'groei',title:L741('Praktijkmaker','Practice maker'),text:L741('Je koppelt leren aan doen.','You link learning to action.'),progress:Math.min(100,practices*50),earned:practices>=2,how:L741('Rond twee praktijkopdrachten af.','Complete two practice assignments.')},
      {id:'exam',icon:'🎓',cat:'Toetsen',tier:'pro',title:L741('Toets gehaald','Test passed'),text:L741('Je hebt kennis gecontroleerd.','You checked your knowledge.'),progress:Math.min(100,exams*100),earned:exams>=1,how:L741('Behaal één toets.','Pass one test.')},
      {id:'agf',icon:'🥬',cat:'AGF',tier:'groei',title:L741('AGF groeier','Produce grower'),text:L741('Je ontwikkelt AGF-vakkennis.','You develop produce expertise.'),progress:pathProgress741('agf').pct,earned:pathProgress741('agf').pct>=50,how:L741('Rond de helft van AGF-lessen af.','Complete half of produce lessons.')},
      {id:'haccp',icon:'🛡️',cat:'HACCP',tier:'groei',title:L741('Risicodenker','Risk thinker'),text:L741('Je begrijpt risico en prioriteit.','You understand risk and priority.'),progress:pathProgress741('haccp').pct,earned:pathProgress741('haccp').pct>=50,how:L741('Rond HACCP-lessen of toets af.','Complete HACCP lessons or test.')},
      {id:'calm',icon:'🌿',cat:'Rust',tier:'basis',title:L741('Rustige keuze','Calm choice'),text:L741('Je kiest volgorde onder druk.','You choose order under pressure.'),progress:pathProgress741('calm').pct,earned:pathProgress741('calm').pct>=50,how:L741('Rond Rust & stress af.','Complete Calm & stress.')},
      {id:'mastery',icon:'🏆',cat:'Mastery',tier:'mastery',title:L741('Leerroute Mastery','Learning route mastery'),text:L741('Je bouwt structureel aan groei.','You build growth structurally.'),progress:Math.min(100,Math.round((done/lessons741().length)*100)),earned:done>=lessons741().length,how:L741('Rond alle v7.4.1 lessen af.','Complete all v7.4.1 lessons.')}
    ]; }
    function badgeCard741(b){ return `<button class="v741-badge ${b.earned?'earned':b.progress>=70?'near':'locked'}" data-action="v741-open-badge" data-id="${E741(b.id)}"><span>${b.icon}</span><strong>${E741(b.title)}</strong><small>${E741(b.text)}</small><i><em style="width:${b.progress}%"></em></i><b>${Math.round(b.progress)}%</b></button>`; }
    function badgesBlock741(){ const st=ensure741(); let list=badges741(); if(st.badgeFilter==='earned') list=list.filter(b=>b.earned); if(st.badgeFilter==='near') list=list.filter(b=>!b.earned&&b.progress>=50); if(st.badgeFilter==='locked') list=list.filter(b=>!b.earned); return `<div class="btn-row mb"><button class="btn ${st.badgeFilter==='all'?'primary':''}" data-action="v741-badge-filter" data-id="all">${E741(L741('Alles','All'))}</button><button class="btn ${st.badgeFilter==='earned'?'primary':''}" data-action="v741-badge-filter" data-id="earned">${E741(L741('Behaald','Earned'))}</button><button class="btn ${st.badgeFilter==='near'?'primary':''}" data-action="v741-badge-filter" data-id="near">${E741(L741('Bijna behaald','Almost earned'))}</button><button class="btn ${st.badgeFilter==='locked'?'primary':''}" data-action="v741-badge-filter" data-id="locked">${E741(L741('Nog te behalen','Not yet'))}</button></div><div class="v741-badge-grid">${list.map(badgeCard741).join('')}</div>`; }
    function adviceBlock741(){ const f=focus741(); return `<div class="v741-advice"><span class="chip">${E741(L741('Leeradvies','Learning advice'))}</span><h3>${E741(f.title)}</h3><p>${E741(f.why)}</p><p class="muted small">${E741(L741('Coaching geeft advies-light. Jij kiest wat past bij je werkdag.','Coaching gives light advice. You choose what fits your day.'))}</p><button class="btn" data-action="v741-path" data-id="${E741(f.path)}">${E741(L741('Open aanbevolen leerpad','Open recommended path'))}</button></div>`; }

    function renderCoaching741(){
      ensure741(); const calm=!!(state.ui&&state.ui.rustMode);
      if(calm) return `<div class="grid coaching-v741 calm"><div class="hero v741-hero"><span class="chip">RICH CMD v7.4.1</span><h2>${E741(L741('Coaching — Rustmodus','Coaching — Calm mode'))}</h2><p>${E741(L741('Alleen voortgang, één aanbevolen les en één leeradvies.','Only progress, one recommended lesson and one learning advice.'))}</p></div>${progress741()}${section741(L741('Aanbevolen voor jou','Recommended for you'),L741('Eén rustige volgende leerstap','One calm next learning step'),recommendedBlock741(),true,'v741-focus')}${section741(L741('Leeradvies','Learning advice'),L741('Gebaseerd op je werkdata','Based on your work data'),adviceBlock741(),true)}</div>`;
      return `<div class="grid coaching-v741"><div class="hero v741-hero"><div><span class="chip">RICH CMD v7.4.1</span><h2>${E741(L741('Coaching Academy Pro','Coaching Academy Pro'))}</h2><p>${E741(L741('Rustiger, leerzamer en motiverender: voortgang bovenaan, lessen prettig leesbaar, toetsen duidelijker en badges compacter.','Calmer, more educational and more motivating: progress at the top, readable lessons, clearer tests and compact badges.'))}</p></div></div>${progress741()}${filters741()}${section741(L741('Aanbevolen voor jou','Recommended for you'),L741('Start hier als je snel wilt leren','Start here if you want to learn quickly'),recommendedBlock741(),true)}${section741(L741('Skill tree','Skill tree'),L741('Compacte leerpaden met voortgang','Compact skill paths with progress'),skillTree741(),true)}${section741(L741('Lessen','Lessons'),L741('MBO-waardige lessen met theorie, praktijk en reflectie','Vocational-level lessons with theory, practice and reflection'),lessonsBlock741(),true)}${section741(L741('Toetsen & examens','Tests & exams'),L741('Score, herkansing en leeradvies','Score, retake and learning advice'),examsBlock741(),false)}${section741(L741('Badgegalerij','Badge gallery'),L741('Behaald, bijna behaald en nog te behalen','Earned, almost earned and not yet earned'),badgesBlock741(),false)}${section741(L741('Leeradvies','Learning advice'),L741('Gekoppeld aan AGF/HACCP/Store Map signalen','Linked to Produce/HACCP/Store Map signals'),adviceBlock741(),true)}</div>`;
    }
    function openLesson741(id){ const l=lessons741().find(x=>x.id===id); if(!l) return; const blocks=[
      [L741('Leerdoel','Learning goal'),l.goal], [L741('Waarom belangrijk','Why it matters'),l.why], [L741('Praktijkvoorbeeld','Practical example'),l.example], [L741('Veelgemaakte fout','Common mistake'),l.mistake], [L741('Stappenplan','Step-by-step'),`<ol>${l.steps.map(s=>`<li>${E741(s)}</li>`).join('')}</ol>`], [L741('Werkvloeropdracht','Shopfloor assignment'),l.assignment], [L741('Reflectie','Reflection'),l.reflect]
    ]; const html=`<div class="v741-lesson-detail"><div class="hero-mini"><span class="chip">${E741((paths741().find(p=>p.id===l.path)||{}).title||l.path)} · ${l.min}m</span><h2>${E741(l.title)}</h2><p>${E741(l.goal)}</p></div><div class="v741-read-flow">${blocks.map((b,i)=>`<section class="card"><span class="pill info">${i+1}/${blocks.length}</span><h3>${E741(b[0])}</h3>${String(b[1]).trim().startsWith('<')?b[1]:`<p>${E741(b[1])}</p>`}</section>`).join('')}</div><div class="btn-row mt"><button class="btn" data-action="v741-practice" data-id="${E741(l.id)}">✓ ${E741(L741('Praktijk gedaan','Practice done'))}</button><button class="btn primary" data-action="v741-complete-lesson" data-id="${E741(l.id)}">${E741(L741('Les afronden','Complete lesson'))}</button><button class="btn" data-action="close-modal">${E741(L741('Sluiten','Close'))}</button></div></div>`; modal741(l.title,html,true); }
    function openBadge741(id){ const b=badges741().find(x=>x.id===id); if(!b) return; modal741(b.title,`<div class="v741-badge-modal ${b.earned?'earned':'locked'}"><div class="v741-badge-big">${b.icon}</div><h2>${E741(b.title)}</h2><p>${E741(b.text)}</p><div class="card soft"><p><strong>${E741(L741('Categorie','Category'))}:</strong> ${E741(b.cat)} · <strong>${E741(L741('Niveau','Tier'))}:</strong> ${E741(b.tier)}</p><p><strong>${E741(L741('Hoe verdien je deze badge?','How do you earn this badge?'))}</strong><br>${E741(b.how)}</p><div class="v741-bar"><span style="width:${b.progress}%"></span></div><p class="muted small">${Math.round(b.progress)}% · ${E741(b.earned?L741('Behaald','Earned'):L741('Nog te behalen','Not yet earned'))}</p></div><button class="btn primary" data-action="close-modal">${E741(L741('Sluiten','Close'))}</button></div>`); }
    function openExam741(id){ const ex=exams741().find(x=>x.id===id); if(!ex) return; ensure741().currentExam={id,answers:{}}; save741(); renderExamModal741(ex); }
    function renderExamModal741(ex){ const st=ensure741(); const ans=(st.currentExam&&st.currentExam.id===ex.id)?(st.currentExam.answers||{}):{}; const all=Object.keys(ans).length>=ex.questions.length; let result=''; if(all){ const score=ex.questions.reduce((a,q,i)=>a+(ans[i]===q.c?1:0),0); const passed=score>=Math.ceil(ex.questions.length*0.67); if(passed && !A741(state.coachingExamPassed).includes(ex.id)) state.coachingExamPassed.push(ex.id); if(passed) save741(); const wrong=ex.questions.map((q,i)=>ans[i]===q.c?null:`<li>${E741(q.q)} — ${E741(q.fb)}</li>`).filter(Boolean).join(''); result=`<div class="card ${passed?'good-card':'warn-card'}"><h3>${passed?'🎉 ':''}${E741(passed?L741('Toets behaald','Test passed'):L741('Nog oefenen','Keep practicing'))}</h3><p>${score}/${ex.questions.length} ${E741(L741('goed','correct'))}.</p>${wrong?`<h4>${E741(L741('Bekijk deze punten nog eens','Review these points'))}</h4><ul>${wrong}</ul>`:''}<div class="btn-row"><button class="btn" data-action="v741-open-exam" data-id="${E741(ex.id)}">${E741(L741('Herkansen','Retake'))}</button><button class="btn primary" data-action="close-modal">${E741(L741('Sluiten','Close'))}</button></div></div>`; }
      const html=`<div class="v741-exam-detail"><div class="hero-mini"><span class="chip">${E741((paths741().find(p=>p.id===ex.path)||{}).title||ex.path)}</span><h2>${E741(ex.title)}</h2><p>${E741(L741('Beantwoord de vragen. Je ziet na afloop score, fouten en leeradvies.','Answer the questions. Afterwards you see score, mistakes and advice.'))}</p></div><div class="grid">${ex.questions.map((q,qi)=>`<div class="card"><h3>${qi+1}. ${E741(q.q)}</h3><div class="grid">${q.a.map((a,ai)=>`<button class="btn ${ans[qi]===ai?'primary':''}" data-action="v741-answer-exam" data-id="${E741(ex.id)}" data-q="${qi}" data-a="${ai}">${E741(a)}</button>`).join('')}</div>${ans[qi]!=null?`<p class="muted small">${E741(q.fb)}</p>`:''}</div>`).join('')}</div>${result}</div>`; modal741(ex.title,html,true); }
    function answerExam741(id,q,a){ const ex=exams741().find(x=>x.id===id); if(!ex) return; const st=ensure741(); st.currentExam=st.currentExam||{id,answers:{}}; if(st.currentExam.id!==id) st.currentExam={id,answers:{}}; st.currentExam.answers[Number(q)]=Number(a); save741(); renderExamModal741(ex); }
    function completeLesson741(id){ if(id&&!A741(state.coachingDone).includes(id)) state.coachingDone.push(id); addActivity741(L741('Coachingles afgerond','Coaching lesson completed')); save741(); close741(); toast741(L741('Les afgerond. Goed bezig.','Lesson completed. Nice work.'),'good'); render741(); }
    function practiceDone741(id){ if(id&&!A741(state.coachingPractices).includes(id)) state.coachingPractices.push(id); addActivity741(L741('Praktijkopdracht afgerond','Practice assignment completed')); save741(); toast741(L741('Praktijkopdracht opgeslagen','Practice assignment saved'),'good'); render741(); }
    function report741(){ const f=focus741(); const earned=badges741().filter(b=>b.earned); return `RICH CMD v7.4.1 — Coaching UX & Learning Quality\n\nLevel: ${level741()}\nXP: ${xp741()}\nVoltooide lessen: ${A741(state.coachingDone).length}\nPraktijkopdrachten: ${A741(state.coachingPractices).length}\nToetsen: ${A741(state.coachingExamPassed).length}\nBadges: ${earned.length}/${badges741().length}\nAanbevolen focus: ${f.title}\nReden: ${f.why}\n\nVolgende les:\n- ${recommended741().title}`; }
    function diagnostics741(){ const checks=[
      {name:'Coaching UX render', ok:typeof renderCoaching==='function', detail:'renderCoaching v7.4.1'},
      {name:'Progressie bovenaan', ok:true, detail:'level/xp/lessen/toetsen/badges'},
      {name:'Inklapbare secties', ok:true, detail:'details/summary'},
      {name:'Lesdetailweergave', ok:lessons741().every(l=>l.why&&l.example&&l.steps&&l.assignment), detail:`${lessons741().length} lessen`},
      {name:'Toetsen met score/herkansing', ok:exams741().length>=4, detail:`${exams741().length} toetsen`},
      {name:'Badgegalerij compact', ok:badges741().length>=6, detail:`${badges741().length} badges`},
      {name:'Rustmodus Coaching', ok:true, detail:'voortgang + aanbevolen les + advies'},
      {name:'Versie/cache', ok:APP.version==='v7.4.1'&&APP.cache==='rich-cmd-cache-v741', detail:`${APP.version} · ${APP.cache}`}
    ]; const score=Math.round(checks.filter(c=>c.ok).length/checks.length*100); return `<div class="card v741-diagnostics"><div class="flex-line"><div><span class="chip">v7.4.1</span><h3>${E741(L741('Coaching UX checks','Coaching UX checks'))}</h3></div><span class="pill ${score>=90?'good':'warn'}">${score}/100</span></div><div class="list mt">${checks.map(c=>`<div class="list-item compact"><span><strong>${E741(c.name)}</strong><br><span class="tiny muted">${E741(c.detail)}</span></span><span class="pill ${c.ok?'good':'warn'}">${c.ok?'OK':'Check'}</span></div>`).join('')}</div><button class="btn mt" data-action="v741-copy-report">${E741(L741('Kopieer coachingrapport','Copy coaching report'))}</button></div>`; }

    const prevCoaching741 = typeof renderCoaching==='function' ? renderCoaching : null;
    renderCoaching = window.renderCoaching = function(){ return renderCoaching741(); };
    const prevVisual741 = typeof renderVisual==='function' ? renderVisual : null;
    if(prevVisual741) renderVisual = window.renderVisual = function(){ return `<div class="grid visual-v741"><div class="card v741-advice"><span class="chip">Coaching UX</span><h3>${E741(L741('Leeradvies rustig gedoseerd','Learning advice calmly dosed'))}</h3><p>${E741(focus741().title)}</p><p class="muted small">${E741(focus741().why)}</p><button class="btn" data-route="coaching">${E741(L741('Open Coaching','Open Coaching'))}</button></div></div>` + prevVisual741(); };
    const prevDiag741 = typeof renderDiagnostics==='function' ? renderDiagnostics : null;
    if(prevDiag741) renderDiagnostics = window.renderDiagnostics = function(){ return `<div class="grid diagnostics-v741">${diagnostics741()}</div>` + prevDiag741(); };
    const prevSettings741 = typeof renderSettings==='function' ? renderSettings : null;
    if(prevSettings741) renderSettings = window.renderSettings = function(){ return prevSettings741() + `<div class="grid mt settings-v741">${diagnostics741()}</div>`; };

    const prevHandle741 = typeof handleAction==='function' ? handleAction : null;
    if(prevHandle741) handleAction = window.handleAction = function(a,el,e){
      if(a==='v741-path'){ ensure741().path=el.dataset.id||'all'; save741(); render741(); return; }
      if(a==='v741-toggle-higher'){ ensure741().showHigher=!ensure741().showHigher; save741(); render741(); return; }
      if(a==='v741-toggle-completed'){ ensure741().showCompleted=!ensure741().showCompleted; save741(); render741(); return; }
      if(a==='v741-open-lesson'){ openLesson741(el.dataset.id); return; }
      if(a==='v741-practice'){ practiceDone741(el.dataset.id); return; }
      if(a==='v741-complete-lesson'){ completeLesson741(el.dataset.id); return; }
      if(a==='v741-open-exam'){ openExam741(el.dataset.id); return; }
      if(a==='v741-answer-exam'){ answerExam741(el.dataset.id, el.dataset.q, el.dataset.a); return; }
      if(a==='v741-open-badge'){ openBadge741(el.dataset.id); return; }
      if(a==='v741-badge-filter'){ ensure741().badgeFilter=el.dataset.id||'all'; save741(); render741(); return; }
      if(a==='v741-copy-report'){ copy741(report741()); return; }
      return prevHandle741(a,el,e);
    };

    ensure741(); save741();
  }catch(err){ console.error('v7.4.1 Coaching UX Polish patch failed', err); }
})();
